extends:
  - airbnb-base
  - plugin:prettier/recommended

# 使用 babel-eslint 替代默认 parser 的主要原因是为了支持 allowImportExportEverywhere 参数
parser: babel-eslint
parserOptions:
  allowImportExportEverywhere: true

# 默认环境设置为 node，再通过 overrides 进行必要的覆盖
env:
  node: true
settings:
  import/resolver: node
rules:
  import/prefer-default-export: 0
  no-param-reassign: 0
  no-use-before-define: 1
  no-underscore-dangle: 0
  no-nested-ternary: 0
  prefer-destructuring: 0
  comma-dangle: 0
  no-shadow: 0
  func-names: 0
  max-len:
    - error
    - code: 200

overrides:
  - files:
      - src/**/*.js
      - src/**/*.ts
    env:
      # src 里的 js/ts 文件最终在浏览器上执行，故环境需要进行相应的修改
      browser: true
      jquery: true

    settings:
      # 使用 eslint-import-resolver-webpack 支持解析 webpack.config.js 中配置的 resolve.alias。
      # 默认会当使用前目录下的 webpack.config.js，需要注意的是到目前为止还不能使用异步的配置函数：https://github.com/import-js/eslint-plugin-import/issues/883。
      # 之前指定过使用 build/webpack.common.js，但在子目录下防止 .eslintrc 后路径会有问题，
      # 所以在当前目录下放置了一个只有这里会用到的 webpack.config.js，同时在里面使用了 @babel/register 使能够正常解析配置文件中的 es6 语法。
      import/resolver: webpack
    rules:
      import/extensions:
        - error
        - always
        - js: never # 强制不加后缀
          ts: never # 强制不加后缀
          mjs: ignorePackages # 可加可不加
          json: ignorePackages # 可加可不加

    # 此处定义了一些预设的常量，各个 page 的 .env.yaml 中定义的常量定义到相应 page 下的 .eslintrc.yaml 中。
    # 详细可以查看 src/pages/oppo/.env.yaml 中的说明
    globals:
      __DEBUG__: readonly
      __DEV__: readonly
      __AEM__: readonly
      __OPPO__: readonly
      __ONEPLUS__: readonly
      __LANG__: readonly
      __ZH__: readonly
      __EN__: readonly
      __GTM_PRODUCT__: readonly
      __GTM_CATEGORY__: readonly

  - files:
      - scripts/*.js
      - scripts/*.ts
    rules:
      no-console: 0
      import/no-extraneous-dependencies: 0

  - files:
      - ./**/*.ts
    parser: '@typescript-eslint/parser'
    plugins:
      - '@typescript-eslint/eslint-plugin'
    extends:
      - 'plugin:@typescript-eslint/recommended'
      - 'prettier'
      - 'plugin:prettier/recommended'
    rules:
      '@typescript-eslint/interface-name-prefix': off
      '@typescript-eslint/explicit-function-return-type': off
      '@typescript-eslint/explicit-module-boundary-types': off
      '@typescript-eslint/no-explicit-any': off
      '@typescript-eslint/no-non-null-assertion': off
